PERF_API_URL: "http://localhost/v2/api/cicd/"
api_params: 
 sla: 
  pageLoadTime: 2000
 baseline: 
  days: 7
  perc: 75
  padding: 1.2
 flags: 
  assertBaseline: true
  debug: false
  esTrace: false
  esCreate: true
  passOnFailedAssert: false
 log: 
  test_info: "Smava Zugangsdaten Page"
  env_tester: "Ubuntu"
  browser: "Chrome"
  env_target: "Prod"
  team: "Smava Zugangsdaten Page"
